<?php
#Example: Contains 7 dimensions with 3 to 6 values each, generates 4 questions/tables

#How many questions/tables shall be generated by this script?
$numberOfTables = 4;

//Store the values as arrays for each dimension
//Index 0: Title of the array

$dimensions = array(
	array('Number of countries',
            '1',
            '2',
            '5', 
            '10', 
            '150'),
        
    array('Countries',
            'China',
            'USA',
            'European Union',
            'India',
            'Russia',
            'Brazil'),

    array('Domestic Sectors that will face further trade liberalization',
            'All',
            'Food and agriculture',
            'ICT',
            'Manufacturing'),

    array('Exporting sectors that will benefit from the agreement',
            'All',
            'Food and agriculture',
            'ICT',
            'Manufacturing'),

    array('Environment',
            'Stricter controls to protect the environment',
            'Make new environmental laws',
            'No environmental commitments'),

    array('Environment',
            'Stricter controls to protect labor rights',
            'Make new labor right protection laws',
            'No labor rights commitments'),

    array('Migration',
            'Low-skilled',
            'High-skilled',
            'No migration commitments')
    );

?>